import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')

function read(relativePath) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('v1.8 admin inventory pool module has API, route, menu, and page', () => {
  assert.equal(existsSync(resolve(root, 'src/api/inventory-pool.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/inventory-pools/index.vue')), true)

  const api = read('src/api/inventory-pool.ts')
  assert.match(api, /getInventoryPools/)
  assert.match(api, /createInventoryPool/)
  assert.match(api, /updateInventoryPool/)
  assert.match(api, /getInventoryPoolBindings/)
  assert.match(api, /createInventoryPoolBinding/)
  assert.match(api, /updateInventoryPoolBinding/)
  assert.match(api, /getInventoryCalendar/)
  assert.match(api, /batchUpdateInventoryCalendar/)
  assert.match(api, /adjustInventoryPool/)
  assert.match(api, /serializeArrayParams/)
  assert.match(api, /search\.append\(key,\s*String\(item\)\)/)
  assert.match(api, /confirmToken/)
  assert.match(api, /X-Confirm-Token/)
  assert.match(api, /\/admin\/inventory\/calendar/)
  assert.match(api, /\/admin\/inventory\/batch-upsert/)
  assert.match(api, /\/admin\/inventory-pools\/\$\{id\}\/adjust/)

  const types = read('src/types/inventory-pool.ts')
  assert.match(types, /InventorySource = 'inventory' \| 'inventory_pool'/)
  assert.match(types, /interface InventoryCalendarCell[\s\S]*inventory_source:\s*InventorySource/)
  assert.match(types, /inventory_pool_id\?:\s*number \| null/)
  assert.match(types, /locked:\s*number/)
  assert.match(types, /sold:\s*number/)
  assert.match(types, /interface InventoryBatchPayload[\s\S]*mode:\s*InventoryBatchMode/)

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'inventory-pools'/)
  assert.match(router, /views\/inventory-pools\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.match(layout, /\/inventory-pools/)
  assert.match(layout, /共享库存/)
  assert.match(layout, /\/inventory-pools', title: '共享库存', roles: \['super_admin'\]/)

  const page = read('src/views/inventory-pools/index.vue')
  assert.match(page, /显式绑定/)
  assert.match(page, /product_id/)
  assert.match(page, /sku_id/)
  assert.match(page, /requestHighRiskConfirm/)
  assert.match(page, /库存数量变化|共享库存不会自动绑定/)
  assert.match(page, /<el-tabs[\s\S]*库存池列表[\s\S]*库存日历/)
  assert.match(page, /批量调整/)
  assert.match(page, /getInventoryCalendar/)
  assert.match(page, /batchUpdateInventoryCalendar/)
  assert.match(page, /adjustInventoryPool/)
  assert.match(page, /requestHighRiskConfirm\('inventory:batch-upsert'[\s\S]*batchForm/)
  assert.match(page, /<el-form-item v-if="batchForm\.mode === 'set_total'" label="总库存">/)
  assert.match(page, /batchForm\.mode === 'set_total'[\s\S]*batchPayload\.total/)
  assert.match(page, /batchForm\.mode === 'open'[\s\S]*batchPayload\.status = 'open'/)
  assert.match(page, /batchForm\.mode === 'close'[\s\S]*batchPayload\.status = 'closed'/)
  assert.doesNotMatch(page, /batchForm\.mode === 'open'[\s\S]{0,120}batchPayload\.total/)
  assert.match(page, /batchTargetType\.value = calendarSkuId\.value \? 'sku' : 'product'/, 'SKU 日历视角打开批量调整时应提交 SKU 目标')
  assert.match(page, /const batchPayload: InventoryBatchPayload = \{[\s\S]*\}\s*if \(batchForm\.weekdays\?\.length\)/, '批量调整 payload 不应写入 undefined 字段参与确认 hash')
  assert.match(page, /const poolDialogWidth = 'min\(560px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const bindingDialogWidth = 'min\(520px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const bindingDrawerSize = 'min\(720px, 92vw\)'/)
  assert.match(page, /const batchDrawerSize = 'min\(520px, 92vw\)'/)
  assert.match(page, /const calendarCellDrawerSize = 'min\(460px, 92vw\)'/)
  assert.doesNotMatch(page, /width="560px"|width="520px"|size="720px"|size="520px"|size="460px"/)
  assert.match(page, /\.stock-grid-item[\s\S]*:deep\(\.el-input-number\)[\s\S]*width:\s*100%/, '库存数量输入应覆盖 Element Plus 默认宽度防止溢出')
  assert.match(page, /row\.cells\[day\]\.status === 'open' \? '开启' : '关闭'/)
  assert.match(page, /requestHighRiskConfirm\([\s\S]*`inventory_pool:adjust:\$\{selectedCalendarPool\.id\}`/)
  assert.match(page, /inventory_source === 'inventory_pool'/)
  assert.doesNotMatch(page, /label="activity_session"/)
  assert.doesNotMatch(page, /label="rental_asset"/)
})

test('v1.8 admin enterprise wechat module has API, route, menu, and page', () => {
  assert.equal(existsSync(resolve(root, 'src/api/enterprise-wechat.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/enterprise-wechat/index.vue')), true)

  const api = read('src/api/enterprise-wechat.ts')
  assert.match(api, /getEnterpriseWechatRobots/)
  assert.match(api, /createEnterpriseWechatRobot/)
  assert.match(api, /updateEnterpriseWechatRobot/)
  assert.match(api, /testSendEnterpriseWechatRobot/)
  assert.match(api, /askSendEnterpriseWechatRobotKnowledge/)
  assert.match(api, /getEnterpriseWechatRobotLogs/)
  assert.match(api, /knowledge-ask-send/)
  assert.match(api, /confirmToken/)
  assert.match(api, /X-Confirm-Token/)

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'enterprise-wechat'/)
  assert.match(router, /views\/enterprise-wechat\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.match(layout, /\/enterprise-wechat/)
  assert.match(layout, /企业微信/)
  assert.match(layout, /\/enterprise-wechat', title: '企业微信', roles: \['super_admin'\]/)

  const page = read('src/views/enterprise-wechat/index.vue')
  assert.match(page, /企业微信群机器人/)
  assert.match(page, /webhook_url/)
  assert.match(page, /requestHighRiskConfirm/)
  assert.match(page, /确认发送测试消息/)
	  assert.match(page, /test-send/)
  assert.match(page, /知识库问答发送/)
  assert.match(page, /askSendEnterpriseWechatRobotKnowledge/)
  assert.match(page, /previewEnterpriseWechatKnowledgeAnswer/)
  assert.match(page, /knowledgeAskPreview/)
  assert.match(page, /knowledgeAskPreview = ref<\{[\s\S]*question:\s*string/, '企业微信群知识库预览结果必须绑定预览时的问题')
  assert.match(page, /knowledgeAskPreview\.value = \{[\s\S]*question,[\s\S]*answer:/, '保存预览结果时应记录当前问题')
  assert.match(page, /knowledgeAskPreview\.value\.question !== question/, '发送前应拒绝使用旧问题的预览答案')
  assert.match(page, /最终答案/)
  assert.match(page, /来源引用/)
  assert.match(page, /人工兜底/)
  assert.match(page, /enterprise_wechat:knowledge_ask_send/)
  assert.match(page, /发送日志/)
  assert.match(page, /toggleRobotStatus[\s\S]*ElMessageBox\.confirm/, '企业微信机器人启停应有确认弹窗')
  assert.match(page, /const dialogWidth = 'min\(560px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const logDialogWidth = 'min\(680px, calc\(100vw - 32px\)\)'/)
  assert.doesNotMatch(page, /width="560px"|width="680px"/, '企业微信弹窗应使用响应式宽度')
	})

test('v1.8 admin customer service AI module manages shared knowledge base and logs', () => {
  assert.equal(existsSync(resolve(root, 'src/api/customer-service-ai.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/types/customer-service-ai.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/customer-service-ai/index.vue')), true)

  const api = read('src/api/customer-service-ai.ts')
  assert.match(api, /getKnowledgeArticles/)
  assert.match(api, /createKnowledgeArticle/)
  assert.match(api, /updateKnowledgeArticle/)
  assert.match(api, /deleteKnowledgeArticle/)
  assert.match(api, /uploadKnowledgeFile/)
  assert.match(api, /headers:\s*\{\s*'Content-Type':\s*undefined\s*\}/, '知识库文件上传不应沿用 application/json Content-Type')
  assert.match(api, /askCustomerServiceKnowledge/)
  assert.match(api, /getCustomerServiceAskLogs/)
  assert.match(api, /\/admin\/customer-service\/knowledge/)
  assert.match(api, /\/admin\/customer-service\/ask/)
  assert.match(api, /\/admin\/customer-service\/ask-logs/)

  const types = read('src/types/customer-service-ai.ts')
  assert.match(types, /CustomerServiceKnowledgeArticle/)
  assert.match(types, /content_format:\s*CustomerServiceKnowledgeFormat/)
  assert.match(types, /source_type:\s*CustomerServiceKnowledgeSourceType/)
  assert.match(types, /CustomerServiceAskResult[\s\S]*sources:\s*CustomerServiceKnowledgeSource\[]/)
  assert.match(types, /needs_human:\s*boolean/)
  assert.match(types, /CustomerServiceAskLog/)

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'customer-service-ai'/)
  assert.match(router, /views\/customer-service-ai\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.match(layout, /\/customer-service-ai/)
  assert.match(layout, /智能客服/)

  const page = read('src/views/customer-service-ai/index.vue')
  assert.match(page, /知识库/)
  assert.match(page, /问答测试/)
  assert.match(page, /问答日志/)
  assert.match(page, /来源引用/)
  assert.match(page, /人工兜底/)
  assert.match(page, /<el-upload[\s\S]*accept="\.txt,\.md,\.pdf,\.docx"/)
  assert.match(page, /uploadKnowledgeFile/)
  assert.match(page, /beforeKnowledgeUpload/)
  assert.match(page, /10 \* 1024 \* 1024/)
  assert.match(page, /askCustomerServiceKnowledge/)
  assert.match(page, /getCustomerServiceAskLogs/)
  assert.match(page, /source_refs|sources/)
  assert.match(page, /needs_human/)
  assert.match(page, /page-header[\s\S]*客服知识库/)
  assert.doesNotMatch(page, /width="760px"|width="680px"/, '智能客服弹窗应使用响应式宽度')
})

test('v1.8 admin order page can create onsite temporary payment sessions', () => {
  const api = read('src/api/order.ts')
  const page = read('src/views/orders/index.vue')
  const types = read('src/types/index.ts')

  assert.match(api, /createTemporaryOrder/)
  assert.match(api, /\/admin\/orders\/temporary/)
  assert.match(api, /queryTemporaryCodePay/)
  assert.match(api, /\/admin\/orders\/temporary\/\$\{sessionId\}\/query-codepay/)
  assert.match(types, /TemporaryOrderCreatePayload/)
  assert.match(types, /TemporaryOrderSession/)
  assert.match(types, /requires_query\?:\s*boolean/)
  assert.match(page, /现场收款/)
  assert.match(page, /showTemporaryOrderDialog/)
  assert.match(page, /temporaryOrderForm/)
  assert.match(page, /payment_flow/)
  assert.match(page, /customer_scan_qr/)
  assert.match(page, /merchant_scan_code/)
  assert.match(page, /auth_code/)
  assert.match(page, /createTemporaryOrder/)
  assert.match(page, /miniapp_path/)
  assert.match(page, /qrcode_image_url/)
  assert.match(page, /<el-image[\s\S]*temporarySession\.qrcode_image_url/)
  assert.match(page, /temporaryQrcodeLoadFailed/)
  assert.match(page, /@error="handleTemporaryQrcodeError"/)
  assert.match(page, /临时收款码/)
  assert.match(page, /付款码收款已提交/)
  assert.match(page, /temporaryResultRequiresQuery/)
  assert.match(page, /handleTemporaryCodePayQuery/)
  assert.match(page, /queryTemporaryCodePay\(temporarySession\.value\.id\)/)
  assert.match(api, /getRefundQueue[\s\S]*\/admin\/refunds/, '退款审批队列应读取 RefundRecord 队列而不是旧订单 refunding 状态')
  assert.match(api, /status:\s*'pending'/, '退款审批队列应筛选 pending RefundRecord')
  assert.match(page, /showRefundQueueDrawer/, '订单页应提供退款队列入口')
  assert.match(page, /refundQueueList/, '订单页应展示 RefundRecord 队列')
  assert.match(page, /approveRefundRecord\(row\.id\)/, '退款审批应按 refund_id 审批')
  assert.match(page, /rejectRefundRecord\(row\.id/, '退款拒绝应按 refund_id 拒绝')
  assert.doesNotMatch(page, /row\.status === 'refunding'[\s\S]{0,180}审批退款/, '退款审批入口不应依赖旧订单状态 refunding')
})

test('v1.8 admin unified product editor covers full product detail fields', () => {
  const api = read('src/api/product.ts')
  const page = read('src/views/products/edit.vue')
  const listPage = read('src/views/products/index.vue')
  const types = read('src/types/index.ts')

  assert.match(api, /getAdminProductDetail/)
  assert.match(api, /\/admin\/products\/\$\{id\}/)
  assert.match(api, /patch\(`/, '商品上下架应使用后端 PATCH 状态接口')
  assert.match(types, /ProductType = 'daily_camping' \| 'event_camping' \| 'rental'/)
  assert.match(types, /ProductStatus = 'draft' \| 'on_sale' \| 'off_sale'/)
  assert.match(types, /interface ProductImage/)
  assert.match(types, /ext_camping\?:\s*CampingExt/)
  assert.match(types, /ext_activity\?:\s*ActivityExt/)
  assert.match(types, /ext_rental\?:\s*RentalExt/)
  assert.match(types, /ext_shop\?:\s*ShopExt/)
  assert.match(types, /interface ProductSkuUpsert/)

  assert.match(page, /<el-tabs[\s\S]*基础信息[\s\S]*详情内容[\s\S]*类型属性[\s\S]*SKU/)
  assert.match(page, /v-model="form\.type"/)
  assert.match(page, /daily_camping/)
  assert.match(page, /event_camping/)
  assert.match(page, /rental/)
  assert.match(page, /daily_activity/)
  assert.match(page, /special_activity/)
  assert.match(page, /shop/)
  assert.match(page, /merchandise/)
  assert.match(page, /v-model="form\.description"/)
  assert.match(page, /safeDescriptionPreview/)
  assert.match(page, /DOMPurify\.sanitize/)
  assert.match(page, /v-html="safeDescriptionPreview"/)
  assert.match(page, /form\.images/)
  assert.match(page, /addImage/)
  assert.match(page, /removeImage/)
  assert.match(page, /ext_camping\.area/)
  assert.match(page, /ext_camping\.position_name/)
  assert.match(page, /ext_camping\.event_start_date/)
  assert.match(page, /ext_activity\.time_slots/)
  assert.match(page, /addTimeSlot/)
  assert.match(page, /ext_rental\.deposit_amount/)
  assert.match(page, /ext_shop\.spec_definitions/)
  assert.match(page, /form\.skus/)
  assert.match(page, /addSku/)
  assert.match(page, /removeSku/)
  assert.match(page, /buildProductPayload/)
  assert.match(page, /on_sale/)
  assert.match(page, /off_sale/)

  assert.match(listPage, /getProductCover/)
  assert.match(listPage, /row\.status === 'on_sale'/)
  assert.doesNotMatch(listPage, /row\.status === 'active'/)
  assert.match(listPage, /formatYuanAmount\(row\.base_price\)/, '商品列表应按后端 Decimal 元金额展示')
  assert.doesNotMatch(listPage, /formatPrice\(row\.base_price\)/, '商品列表不应把后端元金额按分除以 100')
  assert.match(listPage, /\.search-bar[\s\S]*flex-wrap:\s*wrap/, '商品列表筛选栏窄屏应换行')

  assert.match(page, /ensureSkuCode/, 'SKU 编码为空时应在前端生成或阻止提交')
  assert.match(page, /if \(!skuCode\)/, 'SKU 编码生成失败不应提交空编码')
  assert.match(page, /const created = await createProduct/, '新增商品应拿到创建后的商品 ID')
  assert.match(page, /if \(payload\.status && payload\.status !== 'draft'\)[\s\S]*await updateProductStatus/, '新增商品选择上架/下架时应创建后补 PATCH 状态')
  assert.match(page, /throw new Error\('规格定义 JSON 格式错误'\)/, '规格定义 JSON 错误应阻止提交')
  assert.match(page, /throw new Error\(`SKU \$\{row\.sku_code \|\| '未命名'\} 规格 JSON 格式错误`\)/, 'SKU 规格 JSON 错误应阻止提交')
  assert.match(page, /v-model="row\.image_url"/, '统一商品编辑器应维护 SKU 图片字段')
  assert.match(page, /@media \(max-width: 720px\)/, '编辑器固定列布局应提供窄屏兜底')
})

test('v1.8 admin order list maps backend order response and yuan amounts', () => {
  const page = read('src/views/orders/index.vue')
  const types = read('src/types/index.ts')

  assert.match(page, /formatYuanAmount\(row\.total_amount\)/, '订单列表总金额应按后端 Decimal 元展示')
  assert.doesNotMatch(page, /formatPrice\(row\.total_amount\)/, '订单列表不应把后端元金额按分除以 100')
  assert.match(page, /getOrderUserDisplay\(row\)/, '订单列表应兼容后端用户展示字段')
  assert.match(page, /getOrderPhoneDisplay\(row\)/, '订单列表应兼容后端手机号脱敏字段')
  assert.match(page, /getOrderItemCount\(row\)/, '订单列表商品数应由 items 兜底计算')
  assert.match(page, /formatYuanAmount\(row\.refund_amount\)/, '退款队列确认金额应使用 RefundRecord 的退款金额')
  assert.match(types, /actual_amount:\s*number/)
  assert.match(types, /payment_time:\s*string \| null/)
  assert.match(types, /user_phone_masked\?:\s*string \| null/)
})

test('v1.8 admin high-risk modules use super admin only and backend log redaction exists', () => {
  const router = read('src/router/index.ts')
  const highRiskConfirm = read('src/utils/high-risk-confirm.ts')
  const inventoryPage = read('src/views/inventory-pools/index.vue')
  const enterpriseWechatPage = read('src/views/enterprise-wechat/index.vue')
  assert.match(router, /inventory-pools[\s\S]*roles:\s*\['super_admin'\]/)
  assert.match(router, /enterprise-wechat[\s\S]*roles:\s*\['super_admin'\]/)

  const adminRouter = read('../server/routers/admin.py')
  assert.match(adminRouter, /def _redact_enterprise_wechat_log_value/)
  assert.match(adminRouter, /mentioned_mobile_list/)
  assert.match(adminRouter, /def _require_high_risk_confirm/)
  assert.match(adminRouter, /X-Confirm-Token/)
  assert.match(adminRouter, /sku_product_ids/)
  assert.match(adminRouter, /binding_product_id = sku_product_ids\.get\(binding\.sku_id\)/)
  assert.match(adminRouter, /"product_id": binding_product_id/)
  assert.match(adminRouter, /async def create_inventory_pool[\s\S]*_require_high_risk_confirm/)
  assert.match(adminRouter, /async def create_inventory_pool_binding[\s\S]*_require_high_risk_confirm/)
  assert.match(adminRouter, /def _hash_high_risk_body/)
  assert.match(adminRouter, /json\.dumps\([\s\S]*sort_keys=True[\s\S]*separators=\(",",\s*":"\)/)
  assert.match(adminRouter, /hashlib\.sha256/)
  assert.match(adminRouter, /def _get_required_confirm_site_id\(request: Request\) -> int:/, '高风险确认应使用显式站点头解析')
  assert.match(adminRouter, /target_site_id = _get_required_confirm_site_id\(request\)[\s\S]*int\(payload\.get\("site_id"\) or 0\) != target_site_id/, '高风险确认 token 应绑定当前 X-Site-Id 目标站点')
  assert.match(adminRouter, /if not request_hash:/, '高风险写操作必须要求请求内容摘要')

  assert.match(highRiskConfirm, /stableStringify/)
  assert.match(highRiskConfirm, /normalizeJsonPayload/)
  assert.match(highRiskConfirm, /JSON\.parse\(JSON\.stringify\(value \?\? \{\}\)/, '确认 hash 应先按实际 JSON 请求体丢弃 undefined')
  assert.match(highRiskConfirm, /crypto\.subtle\.digest\('SHA-256'/)
  assert.match(highRiskConfirm, /request_hash/)
  assert.match(highRiskConfirm, /payload\?:\s*unknown/)

  assert.match(inventoryPage, /requestHighRiskConfirm\(action,\s*quantityChange,\s*payload\)/, '库存池保存确认应绑定实际提交 payload')
  assert.match(inventoryPage, /requestHighRiskConfirm\([\s\S]*`inventory_pool:adjust:\$\{row\.id\}`[\s\S]*payload/, '库存池启停确认应绑定共享池调整 payload')
  assert.match(inventoryPage, /requestHighRiskConfirm\([\s\S]*action[\s\S]*payload[\s\S]*\)/, '库存池绑定确认应绑定实际提交 payload')
  assert.match(inventoryPage, /deriveBindingProductId/, '编辑 SKU 绑定时应能恢复所属商品上下文')
  assert.match(enterpriseWechatPage, /const payload = buildRobotPayload\(\)[\s\S]*requestHighRiskConfirm\([\s\S]*payload/, '企业微信机器人保存确认应绑定实际提交 payload')
  assert.match(enterpriseWechatPage, /requestHighRiskConfirm\([\s\S]*`enterprise_wechat:update:\$\{row\.id\}`[\s\S]*\{\s*status\s*\}/, '企业微信机器人启停确认应绑定状态 payload')
  assert.match(enterpriseWechatPage, /const payload = \{[\s\S]*mentioned_mobile_list[\s\S]*requestHighRiskConfirm\([\s\S]*payload/, '企业微信测试发送确认应绑定消息 payload')
	assert.match(enterpriseWechatPage, /async function toggleRobotStatus[\s\S]*try \{[\s\S]*ElMessageBox\.confirm[\s\S]*requestHighRiskConfirm[\s\S]*\} catch \{[\s\S]*return[\s\S]*\}/, '企业微信机器人启停取消时不应产生未处理 Promise rejection')
})

test('v1.8 admin membership card module has unified entry, aggregated types, and legacy compat routes', () => {
  const api = read('src/api/member.ts')
  const types = read('src/types/index.ts')
  const router = read('src/router/index.ts')
  const layout = read('src/layout/index.vue')
  const listPage = read('src/views/members/index.vue')
  const detailPage = read('src/views/members/detail.vue')
  const unifiedPage = read('src/views/members/membership-cards.vue')
  const annualPage = read('src/views/members/annual-cards.vue')
  const timesPage = read('src/views/members/times-cards.vue')

  assert.match(api, /getMembershipCards|membership_cards/)
  assert.match(api, /getMembers/)
  assert.match(api, /getMemberDetail/)
  assert.match(types, /membership_cards:\s*MembershipCardInfo\[]/)
  assert.match(types, /membership_card_count:\s*number/)
  assert.match(types, /has_membership_card:\s*boolean/)
  assert.match(types, /interface MembershipCardInfo[\s\S]*card_type:\s*'annual' \| 'times'/)
  assert.match(types, /use_mode:\s*string/)
  assert.match(types, /valid_until:\s*string \| null/)
  assert.match(types, /remaining_days:\s*number \| null/)
  assert.match(types, /remaining_times:\s*number \| null/)
  assert.match(types, /applicable_products:\s*string\[]/)
  assert.match(router, /title:\s*'会员卡'/)
  assert.match(router, /title:\s*'会员卡详情'/)
  assert.match(router, /title:\s*'会员卡配置'/)
  assert.match(router, /path:\s*'members'/)
  assert.match(router, /path:\s*'members\/:id'/)
  assert.match(router, /path:\s*'annual-cards'/)
  assert.match(router, /path:\s*'times-cards'/)
  assert.match(layout, /title:\s*'会员卡'/)
  assert.match(layout, /会员卡总览/)
  assert.match(layout, /年卡配置/)
  assert.match(layout, /次数卡配置/)
  assert.match(listPage, /会员卡/)
  assert.match(listPage, /membership_cards/)
  assert.match(listPage, /membership_card_count/)
  assert.match(listPage, /has_membership_card/)
  assert.match(listPage, /<el-tabs/)
  assert.match(listPage, /年卡/)
  assert.match(listPage, /次数卡/)
  assert.match(detailPage, /会员卡详情/)
  assert.match(detailPage, /membership_cards/)
  assert.match(detailPage, /剩余天数/)
  assert.match(detailPage, /剩余次数/)
  assert.match(detailPage, /适用商品/)
  assert.match(detailPage, /使用模式/)
  assert.match(unifiedPage, /会员卡/)
  assert.match(unifiedPage, /会员卡总览/)
  assert.match(unifiedPage, /年卡配置/)
  assert.match(unifiedPage, /次数卡配置/)
  assert.match(unifiedPage, /membership_cards/)
  assert.match(unifiedPage, /annual/)
  assert.match(unifiedPage, /times/)
  assert.match(unifiedPage, /卡种/)
  assert.match(unifiedPage, /使用模式/)
  assert.match(unifiedPage, /有效期/)
  assert.match(unifiedPage, /剩余天数|剩余次数/)
  assert.match(unifiedPage, /适用商品/)
  assert.match(unifiedPage, /状态/)
  assert.match(annualPage, /兼容入口|会员卡/)
  assert.match(timesPage, /兼容入口|会员卡/)
  assert.match(annualPage, /membership-cards|会员卡/)
  assert.match(timesPage, /membership-cards|会员卡/)
  assert.doesNotMatch(listPage, /年卡管理|次数卡管理/)
  assert.doesNotMatch(detailPage, /年卡信息|次数卡信息/)
})

test('admin requests carry site isolation header for v1.8 multi-campsite APIs', () => {
  const request = read('src/utils/request.ts')

  assert.match(request, /X-Site-Id/)
  assert.match(request, /admin_site_id/)
  assert.match(request, /VITE_SITE_ID/)
  assert.match(request, /auth\/refresh[\s\S]*headers:\s*\{\s*'X-Site-Id':\s*getCurrentSiteId\(\)\s*\}/)
})

test('camp map admin supports hotspot links and click metrics', () => {
  const page = read('src/views/camp-map/index.vue')
  const types = read('src/types/index.ts')

  assert.match(types, /link_type/, '地图区域类型应声明链接类型')
  assert.match(types, /link_target/, '地图区域类型应声明链接目标')
  assert.match(types, /click_count/, '地图区域类型应声明点击次数')
  assert.match(page, /linkTypeOptions/, '地图区域表单应提供链接类型选项')
  assert.match(page, /zoneForm\.link_target/, '地图区域表单应配置链接目标')
  assert.match(page, /prop="click_count"/, '地图区域列表应展示点击次数')
  assert.match(page, /value="image"/, '地图类型应使用后端支持的 image')
  assert.match(page, /value="svg"/, '地图类型应使用后端支持的 svg')
  assert.doesNotMatch(page, /value="plan"|value="satellite"|value="illustration"/, '地图类型不应提交后端不支持的枚举')
  assert.match(page, /action="\/api\/v1\/admin\/cms\/assets\/upload"/, '地图图片上传应复用已存在的 CMS 素材上传接口')
  assert.match(page, /'X-Site-Id':\s*getCurrentSiteId\(\)/, '地图图片上传应携带当前营地站点头')
  assert.match(page, /validateZoneLink/, '地图热区链接应有基础格式校验')
  assert.match(page, /zoneForm\.link_type === 'product'[\s\S]*<el-select[\s\S]*v-model="zoneForm\.link_target"/, '商品热区链接目标应使用商品下拉选择器')
  assert.match(page, /selectedProductIds\.has\(target\)/, '商品热区链接目标应校验来自商品列表')
  assert.doesNotMatch(page, /商品链接目标必须填写商品ID/, '商品热区链接不应要求运营手填商品ID')
  assert.match(page, /map-zone-overlay/, '后台地图预览应叠加展示热区框，便于运营校准坐标')
  assert.match(page, /class="map-preview-canvas"[\s\S]*<img[\s\S]*class="map-image"/, '热区预览应锚定真实图片元素，而不是 el-image contain 留白容器')
  assert.match(page, /\.map-preview-canvas[\s\S]*display:\s*inline-block/, '热区预览容器应由图片实际尺寸撑开')
  assert.match(page, /validateZoneCoordinates/, '地图热区坐标应有越界校验')
  assert.match(page, /x \+ width/, '坐标校验应限制热区宽度不能超出底图')
  assert.match(page, /y \+ height/, '坐标校验应限制热区高度不能超出底图')
  assert.match(types, /CampMapType = 'image' \| 'svg'/, '地图类型应在 TS 层收窄为后端枚举')
  assert.equal(page.includes("!/^https:\\/\\//.test(target)"), true, 'H5 热区链接应限制 HTTPS')
  assert.match(page, /H5 链接必须以 https:\/\/ 开头/, 'H5 热区链接应给出 HTTPS 提示')
  assert.match(page, /\.coordinates-row[\s\S]*flex-wrap:\s*wrap/, '坐标输入在窄屏弹窗内应允许换行')
  assert.match(page, /flex:\s*1 1 110px/, '坐标输入宽度应响应式伸缩')
  assert.match(page, /商品列表加载失败/, '商品链接下拉加载失败时应提示运营')
})

test('reports page exposes page view analytics', () => {
  const reportsPage = read('src/views/reports/index.vue')
  const systemApi = read('src/api/system.ts')

  assert.match(systemApi, /getPageViewStats/, '后台应封装页面浏览统计 API')
  assert.match(systemApi, /\/admin\/analytics\/page-views/, '页面浏览统计 API 路径应正确')
  assert.match(systemApi, /summary:\s*PageViewSummary/, '页面浏览统计响应应包含后端全量聚合摘要')
  assert.match(reportsPage, /value="page_views"/, '报表页应有页面浏览类型入口')
  assert.match(reportsPage, /getPageViewStats/, '报表页应拉取页面浏览统计')
  assert.match(reportsPage, /pageViewSummary/, '报表页应展示页面浏览摘要')
  assert.doesNotMatch(reportsPage, /reduce\(\(sum,\s*item\)\s*=>\s*sum \+ item\.view_count/, '页面浏览摘要不应从第一页列表汇总')
})
