import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')

function read(relativePath) {
  return readFileSync(resolve(root, relativePath), 'utf8')
}

test('v1.8 admin inventory pool module keeps API route and page while menu is hidden', () => {
  assert.equal(existsSync(resolve(root, 'src/api/inventory-pool.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/inventory-pools/index.vue')), true)

  const api = read('src/api/inventory-pool.ts')
  assert.match(api, /getInventoryPools/)
  assert.match(api, /createInventoryPool/)
  assert.match(api, /updateInventoryPool/)
  assert.match(api, /getInventoryPoolBindings/)
  assert.match(api, /createInventoryPoolBinding/)
  assert.match(api, /updateInventoryPoolBinding/)
  assert.match(api, /getInventoryCalendar/)
  assert.match(api, /batchUpdateInventoryCalendar/)
  assert.match(api, /adjustInventoryPool/)
  assert.match(api, /serializeArrayParams/)
  assert.match(api, /search\.append\(key,\s*String\(item\)\)/)
  assert.doesNotMatch(api, /confirmToken/, '库存池接口不属于指定高风险操作，不应再要求二次确认 token')
  assert.doesNotMatch(api, /X-Confirm-Token/, '库存池接口不属于指定高风险操作，不应再发送二次确认 token')
  assert.match(api, /\/admin\/inventory\/calendar/)
  assert.match(api, /\/admin\/inventory\/batch-upsert/)
  assert.match(api, /\/admin\/inventory-pools\/\$\{id\}\/adjust/)

  const types = read('src/types/inventory-pool.ts')
  assert.match(types, /InventorySource = 'inventory' \| 'inventory_pool'/)
  assert.match(types, /interface InventoryCalendarCell[\s\S]*inventory_source:\s*InventorySource/)
  assert.match(types, /inventory_pool_id\?:\s*number \| null/)
  assert.match(types, /locked:\s*number/)
  assert.match(types, /sold:\s*number/)
  assert.match(types, /InventoryBatchContent = 'inventory' \| 'price' \| 'both'/)
  assert.match(types, /InventoryBatchPriceMode = 'set_total' \| 'adjust_total'/)
  assert.match(types, /interface InventoryBatchPayload[\s\S]*mode:\s*InventoryBatchMode/)
  assert.match(types, /adjust_inventory\?:\s*boolean/)
  assert.match(types, /price_mode\?:\s*InventoryBatchPriceMode/)
  assert.match(types, /price_total\?:\s*number/)
  assert.match(types, /price_delta\?:\s*number/)

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'inventory-pools'/)
  assert.match(router, /views\/inventory-pools\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.doesNotMatch(layout, /\/inventory-pools/, '新需求要求运营管理侧栏隐藏共享库存入口')
  assert.doesNotMatch(layout, /\/inventory-pools', title: '共享库存'/, '共享库存路由保留但不在侧栏单独展示')

  const page = read('src/views/inventory-pools/index.vue')
  assert.match(page, /显式绑定/)
  assert.match(page, /product_id/)
  assert.match(page, /sku_id/)
  assert.match(page, /ElMessageBox\.confirm/)
  assert.match(page, /库存数量变化|共享库存不会自动绑定/)
  assert.match(page, /<el-tabs[\s\S]*库存池列表[\s\S]*商品日历/)
  assert.match(page, /批量调整/)
  assert.match(page, /getInventoryCalendar/)
  assert.match(page, /batchUpdateInventoryCalendar/)
  assert.match(page, /adjustInventoryPool/)
  assert.match(page, /ElMessageBox\.confirm[\s\S]*商品日历批量调整确认/)
  assert.match(page, /<el-select v-model="batchForm\.row_keys" multiple/, '库存池内嵌商品日历批量调整应支持多选当前行')
  assert.match(page, /:shortcuts="batchDateShortcuts"/, '批量日期范围应提供最近一个月/三个月/半年/一年快捷')
  assert.match(page, /batchDateMode/, '库存池内嵌商品日历应支持日期范围和离散日期两种批量选择模式')
  assert.match(page, /type="dates"/, '库存池内嵌商品日历应支持批量选择多个离散日期')
  assert.match(page, /batchPayload\.dates = \[...batchSelectedDates\.value\]/, '离散日期模式应提交 dates 数组而不是仅提交连续范围')
  assert.match(page, /最近一个月/)
  assert.match(page, /最近三个月/)
  assert.match(page, /最近半年/)
  assert.match(page, /最近一年/)
  assert.match(page, /batchForm\.content/, '批量调整应支持库存/价格/库存+价格内容选择')
  assert.match(page, /<el-radio-button label="inventory">库存<\/el-radio-button>/)
  assert.match(page, /<el-radio-button label="price">价格<\/el-radio-button>/)
  assert.match(page, /<el-radio-button label="both">库存\+价格<\/el-radio-button>/)
  assert.match(page, /<el-form-item v-if="batchForm\.mode === 'set_total'" label="总库存">/)
  assert.match(page, /batchForm\.mode === 'set_total'[\s\S]*batchPayload\.total/)
  assert.match(page, /batchForm\.mode === 'open'[\s\S]*batchPayload\.status = 'open'/)
  assert.match(page, /batchForm\.mode === 'close'[\s\S]*batchPayload\.status = 'closed'/)
  assert.doesNotMatch(page, /batchForm\.mode === 'open'[\s\S]{0,120}batchPayload\.total/)
  assert.match(page, /batchForm\.price_mode/, '批量调价应支持价格模式')
  assert.match(page, /batchForm\.price_total/, '批量调价应支持目标总价')
  assert.match(page, /batchForm\.price_delta/, '批量调价应支持价格增减')
  assert.match(page, /selectedTargets = calendarRows\.value\.filter\(row => batchForm\.row_keys\.includes\(row\.row_key\)\)/, '批量调整应基于当前商品日历行多选目标')
  assert.match(page, /adjust_inventory:\s*batchForm\.content !== 'price'/, '仅调价格时不应调整库存')
  assert.match(page, /hasSharedTargets[\s\S]*batchForm\.content !== 'price'/, '共享库存行应仅在库存调整模式被拦截，价格模式可批量调价')
  assert.match(page, /hasSkuTargets[\s\S]*hasProductLevelTargets[\s\S]*不能混选/, '商品级行和 SKU 行不能混选，避免后端只处理 SKU target 导致静默漏改')
  assert.match(page, /batchPayload\.price_mode = batchForm\.price_mode/, '批量价格 payload 应带价格模式')
  assert.match(page, /batchPayload\.price_total = batchForm\.price_total/, '总价模式应提交目标总价')
  assert.match(page, /batchPayload\.price_delta = batchForm\.price_delta/, '增减模式应提交价格增减')
  assert.match(page, /price_created_count.*price_updated_count|price_updated_count.*price_created_count/, '批量结果提示应包含价格新增/更新数量')
  assert.match(page, /<el-form-item v-if="batchDateMode === 'range'" label="星期">/, '离散日期模式不应展示星期筛选，避免误导运营')
  assert.match(page, /const batchPayload: InventoryBatchPayload = \{[\s\S]*\}\s*if \(batchDateMode\.value === 'range' && batchForm\.weekdays\?\.length\)/, '批量调整 payload 不应写入 undefined 字段或对离散日期附加星期筛选')
  assert.match(page, /isToday\(day\)/, '日历表头应识别今天')
  assert.match(page, /今天/, '日历今天应有文字标注')
  assert.match(page, /calendar-column--today|calendar-cell--today/, '今天列应有视觉高亮 class')
  assert.match(page, /const poolDialogWidth = 'min\(560px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const bindingDialogWidth = 'min\(520px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const bindingDrawerSize = 'min\(720px, 92vw\)'/)
  assert.match(page, /const batchDrawerSize = 'min\(520px, 92vw\)'/)
  assert.match(page, /const calendarCellDrawerSize = 'min\(460px, 92vw\)'/)
  assert.doesNotMatch(page, /width="560px"|width="520px"|size="720px"|size="520px"|size="460px"/)
  assert.match(page, /\.stock-grid-item[\s\S]*:deep\(\.el-input-number\)[\s\S]*width:\s*100%/, '库存数量输入应覆盖 Element Plus 默认宽度防止溢出')
  assert.match(page, /row\.cells\[day\]\.status === 'open' \? '开启' : '关闭'/)
  assert.match(page, /ElMessageBox\.confirm[\s\S]*共享库存调整确认/)
  assert.match(page, /inventory_source === 'inventory_pool'/)
  assert.doesNotMatch(page, /label="activity_session"/)
  assert.doesNotMatch(page, /label="rental_asset"/)
})

test('v1.8 admin inventory calendar covers campsite activity and rental products', () => {
  const page = read('src/views/calendar/index.vue')
  const router = read('src/router/index.ts')
  const layout = read('src/layout/index.vue')

  assert.match(page, /商品日历/, '商品日历标题应覆盖营位、活动、租赁')
  assert.match(page, /calendarProductType/, '商品日历应维护商品类型筛选')
  assert.match(page, /calendarTypeOptions/, '商品日历应提供类型选项')
  assert.match(page, /daily_camping/, '商品日历应支持日常营位')
  assert.match(page, /event_camping/, '商品日历应支持活动营位')
  assert.match(page, /daily_activity/, '商品日历应支持日常活动')
  assert.match(page, /special_activity/, '商品日历应支持特定活动')
  assert.match(page, /rental/, '商品日历应支持租赁')
  assert.match(page, /v-model="calendarProductType"/, '页面应有可切换商品类型的控件')
  assert.match(page, /product_type:\s*calendarProductType\.value/, '商品日历查询应按所选类型请求')
  assert.doesNotMatch(page, /product_type:\s*'daily_camping'/, '商品日历不应写死日常营位')
  assert.match(page, /selectedTypeLabel/, '弹窗和文案应跟随当前类型')
  assert.match(page, /:placeholder="`请选择\$\{selectedTypeLabel\}`"/, '批量调整应按当前类型提示选择商品')
  assert.match(page, /确认批量调整 \${getBatchDateSummary\(\)} 的\${selectedTypeLabel\.value}？/, '批量调整确认文案应带当前类型')
  assert.match(page, /product_type:\s*calendarProductType\.value,[\s\S]*booking_date_start/, '当天订单查询应带商品类型和预约日期')
  assert.match(page, /rowKey = `\$\{cell\.product_id\}:\$\{cell\.sku_id \|\| 0\}:\$\{cell\.time_slot \|\| ''\}:\$\{cell\.inventory_source\}`/, '商品日历行应按商品、SKU、场次和库存来源区分')
  assert.match(page, /time_slot:\s*cell\.time_slot \|\| null/, '日历行应保留活动场次维度')
  assert.match(page, /:label="formatBatchTargetLabel\(row\)"/, '批量调整选项应展示 SKU/场次行级目标')
  assert.match(page, /selectedTargets = productRows\.value\.filter\(row => batchForm\.row_keys\.includes\(row\.row_key\)\)/, '批量调整应支持选择多个当前日历行目标')
  assert.match(page, /batchDateMode/, '商品日历应支持日期范围和离散日期两种批量选择模式')
  assert.match(page, /type="dates"/, '商品日历批量调整应支持选择多个离散日期')
  assert.match(page, /payload\.dates = \[...batchSelectedDates\.value\]/, '商品日历离散日期模式应提交 dates 数组')
  assert.match(page, /hasSharedTargets[\s\S]*batchForm\.content !== 'price'/, '共享库存行只应限制库存调整，不应限制批量调价')
  assert.doesNotMatch(page, /:disabled="row\.inventory_source === 'inventory_pool'"/, '共享库存行不应在目标选择阶段直接禁用，否则无法批量调价')
  assert.match(page, /hasSkuTargets[\s\S]*hasProductLevelTargets[\s\S]*不能混选/, '商品级行和 SKU 行不能混选，避免后端只处理 SKU target 导致静默漏改')
  assert.match(page, /sku_ids:\s*hasSkuTargets \? skuIds : undefined/, '批量调整 SKU 行应提交 sku_ids')
  assert.match(page, /time_slot:\s*timeSlots\[0\] \|\| undefined/, '批量调整活动场次行应提交 time_slot')
  assert.match(page, /sku_id:\s*selectedCell\.value\.sku_id \|\| undefined/, '当天订单查询应带 SKU 过滤')
  assert.match(page, /time_slot:\s*selectedCell\.value\.time_slot \|\| undefined/, '当天订单查询应带活动场次过滤')
  assert.match(page, /emptyDescription/, '空状态应按当前类型显示')
  assert.match(router, /calendar[\s\S]*title:\s*'商品日历'/, '路由标题应从营位日历升级为商品日历')
  assert.match(layout, /\/calendar', title: '商品日历'/, '菜单标题应从营位日历升级为商品日历')
})

test('v1.8 admin product grouped filters cover every concrete product type', () => {
  const page = read('src/views/products/index.vue')
  const api = read('src/api/product.ts')
  const types = read('src/types/index.ts')
  const schema = read('../server/schemas/product.py')
  const router = read('../server/routers/products.py')
  const service = read('../server/services/product_service.py')

  assert.match(types, /types\?:\s*ProductType\[]/, '商品搜索参数应支持多商品类型筛选')
  assert.match(api, /paramsSerializer[\s\S]*serializeArrayParams/, '商品列表 API 应序列化数组查询参数')
  assert.match(page, /campsite:\s*\['daily_camping',\s*'event_camping'\]/, '营位聚合筛选应覆盖日常营位和活动营位')
  assert.match(page, /activity:\s*\['daily_activity',\s*'special_activity'\]/, '活动聚合筛选应覆盖日常活动和特定活动')
  assert.match(page, /product:\s*\['shop',\s*'merchandise'\]/, '商品聚合筛选应覆盖现场商品和周边商品')
  assert.match(page, /searchParams\.types = nextTypes/, '聚合入口应写入多类型查询参数')
  assert.match(page, /delete searchParams\.types/, '切换到具体类型或全部时应清理多类型查询参数')
  assert.match(schema, /types:\s*Optional\[List\[str\]\]/, '后端商品筛选 schema 应声明 types 数组')
  assert.match(router, /product_types=params\.types/, '商品路由应把 types 传给服务层')
  assert.match(service, /product_types:\s*Optional\[List\[str\]\]/, '商品服务应接受多类型参数')
  assert.match(service, /Product\.type\.in_\(product_types\)/, '商品服务应使用 IN 查询覆盖聚合类型')
})

test('v1.8 admin enterprise wechat module has API, route, menu, and page', () => {
  assert.equal(existsSync(resolve(root, 'src/api/enterprise-wechat.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/enterprise-wechat/index.vue')), true)

  const api = read('src/api/enterprise-wechat.ts')
  assert.match(api, /getEnterpriseWechatRobots/)
  assert.match(api, /createEnterpriseWechatRobot/)
  assert.match(api, /updateEnterpriseWechatRobot/)
  assert.match(api, /testSendEnterpriseWechatRobot/)
  assert.match(api, /askSendEnterpriseWechatRobotKnowledge/)
  assert.match(api, /getEnterpriseWechatRobotLogs/)
  assert.match(api, /knowledge-ask-send/)
  assert.doesNotMatch(api, /confirmToken/, '企业微信接口不属于本轮指定高风险操作，不应再要求二次确认 token')
  assert.doesNotMatch(api, /X-Confirm-Token/, '企业微信接口不属于本轮指定高风险操作，不应再发送二次确认 token')

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'enterprise-wechat'/)
  assert.match(router, /views\/enterprise-wechat\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.match(layout, /\/enterprise-wechat/)
  assert.match(layout, /企业微信/)
  assert.match(layout, /\/enterprise-wechat', title: '企业微信', roles: \['super_admin'\]/)

  const page = read('src/views/enterprise-wechat/index.vue')
  assert.match(page, /企业微信群机器人/)
  assert.match(page, /webhook_url/)
  assert.match(page, /ElMessageBox\.confirm/)
  assert.match(page, /确认发送测试消息/)
	  assert.match(page, /test-send/)
  assert.match(page, /知识库问答发送/)
  assert.match(page, /askSendEnterpriseWechatRobotKnowledge/)
  assert.match(page, /previewEnterpriseWechatKnowledgeAnswer/)
  assert.match(page, /knowledgeAskPreview/)
  assert.match(page, /knowledgeAskPreview = ref<\{[\s\S]*question:\s*string/, '企业微信群知识库预览结果必须绑定预览时的问题')
  assert.match(page, /knowledgeAskPreview\.value = \{[\s\S]*question,[\s\S]*answer:/, '保存预览结果时应记录当前问题')
  assert.match(page, /knowledgeAskPreview\.value\.question !== question/, '发送前应拒绝使用旧问题的预览答案')
  assert.match(page, /最终答案/)
  assert.match(page, /来源引用/)
  assert.match(page, /人工兜底/)
  assert.match(page, /知识库问答发送/)
  assert.match(page, /发送日志/)
  assert.match(page, /toggleRobotStatus[\s\S]*ElMessageBox\.confirm/, '企业微信机器人启停应有确认弹窗')
  assert.match(page, /const dialogWidth = 'min\(560px, calc\(100vw - 32px\)\)'/)
  assert.match(page, /const logDialogWidth = 'min\(680px, calc\(100vw - 32px\)\)'/)
  assert.doesNotMatch(page, /width="560px"|width="680px"/, '企业微信弹窗应使用响应式宽度')
	})

test('v1.8 admin customer service AI module manages shared knowledge base and logs', () => {
  assert.equal(existsSync(resolve(root, 'src/api/customer-service-ai.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/types/customer-service-ai.ts')), true)
  assert.equal(existsSync(resolve(root, 'src/views/customer-service-ai/index.vue')), true)

  const api = read('src/api/customer-service-ai.ts')
  assert.match(api, /getKnowledgeArticles/)
  assert.match(api, /createKnowledgeArticle/)
  assert.match(api, /updateKnowledgeArticle/)
  assert.match(api, /deleteKnowledgeArticle/)
  assert.match(api, /uploadKnowledgeFile/)
  assert.match(api, /headers:\s*\{\s*'Content-Type':\s*undefined\s*\}/, '知识库文件上传不应沿用 application/json Content-Type')
  assert.match(api, /askCustomerServiceKnowledge/)
  assert.match(api, /getCustomerServiceAskLogs/)
  assert.match(api, /\/admin\/customer-service\/knowledge/)
  assert.match(api, /\/admin\/customer-service\/ask/)
  assert.match(api, /\/admin\/customer-service\/ask-logs/)

  const types = read('src/types/customer-service-ai.ts')
  assert.match(types, /CustomerServiceKnowledgeArticle/)
  assert.match(types, /content_format:\s*CustomerServiceKnowledgeFormat/)
  assert.match(types, /source_type:\s*CustomerServiceKnowledgeSourceType/)
  assert.match(types, /CustomerServiceAskResult[\s\S]*sources:\s*CustomerServiceKnowledgeSource\[]/)
  assert.match(types, /needs_human:\s*boolean/)
  assert.match(types, /CustomerServiceAskLog/)

  const router = read('src/router/index.ts')
  assert.match(router, /path:\s*'customer-service-ai'/)
  assert.match(router, /views\/customer-service-ai\/index\.vue/)

  const layout = read('src/layout/index.vue')
  assert.match(layout, /\/customer-service-ai/)
  assert.match(layout, /智能客服/)

  const page = read('src/views/customer-service-ai/index.vue')
  assert.match(page, /知识库/)
  assert.match(page, /问答测试/)
  assert.match(page, /问答日志/)
  assert.match(page, /来源引用/)
  assert.match(page, /人工兜底/)
  assert.match(page, /<el-upload[\s\S]*accept="\.txt,\.md,\.pdf,\.docx"/)
  assert.match(page, /uploadKnowledgeFile/)
  assert.match(page, /beforeKnowledgeUpload/)
  assert.match(page, /10 \* 1024 \* 1024/)
  assert.match(page, /askCustomerServiceKnowledge/)
  assert.match(page, /getCustomerServiceAskLogs/)
  assert.match(page, /source_refs|sources/)
  assert.match(page, /needs_human/)
  assert.match(page, /page-header[\s\S]*客服知识库/)
  assert.doesNotMatch(page, /width="760px"|width="680px"/, '智能客服弹窗应使用响应式宽度')
})

test('v1.8 admin order page can create onsite temporary payment sessions', () => {
  const api = read('src/api/order.ts')
  const page = read('src/views/orders/index.vue')
  const types = read('src/types/index.ts')

  assert.match(api, /createTemporaryOrder/)
  assert.match(api, /\/admin\/orders\/temporary/)
  assert.match(api, /queryTemporaryCodePay/)
  assert.match(api, /\/admin\/orders\/temporary\/\$\{sessionId\}\/query-codepay/)
  assert.match(types, /TemporaryOrderCreatePayload/)
  assert.match(types, /TemporaryOrderSession/)
  assert.match(types, /requires_query\?:\s*boolean/)
  assert.match(page, /现场收款/)
  assert.match(page, /showTemporaryOrderDialog/)
  assert.match(page, /temporaryOrderForm/)
  assert.match(page, /payment_flow/)
  assert.match(page, /customer_scan_qr/)
  assert.match(page, /merchant_scan_code/)
  assert.match(page, /auth_code/)
  assert.match(page, /createTemporaryOrder/)
  assert.match(page, /miniapp_path/)
  assert.match(page, /qrcode_image_url/)
  assert.match(page, /<el-image[\s\S]*temporarySession\.qrcode_image_url/)
  assert.match(page, /temporaryQrcodeLoadFailed/)
  assert.match(page, /@error="handleTemporaryQrcodeError"/)
  assert.match(page, /临时收款码/)
  assert.match(page, /付款码收款已提交/)
  assert.match(page, /temporaryResultRequiresQuery/)
  assert.match(page, /handleTemporaryCodePayQuery/)
  assert.match(page, /queryTemporaryCodePay\(temporarySession\.value\.id\)/)
  assert.match(api, /getRefundQueue[\s\S]*\/admin\/refunds/, '退款审批队列应读取 RefundRecord 队列而不是旧订单 refunding 状态')
  assert.match(api, /status:\s*'pending'/, '退款审批队列应筛选 pending RefundRecord')
  assert.match(page, /showRefundQueueDrawer/, '订单页应提供退款队列入口')
  assert.match(page, /refundQueueList/, '订单页应展示 RefundRecord 队列')
  assert.match(page, /approveRefundRecord\(row\.id\)/, '退款审批应按 refund_id 审批')
  assert.match(page, /rejectRefundRecord\(row\.id/, '退款拒绝应按 refund_id 拒绝')
  assert.doesNotMatch(page, /row\.status === 'refunding'[\s\S]{0,180}审批退款/, '退款审批入口不应依赖旧订单状态 refunding')
})

test('v1.8 admin unified product editor covers full product detail fields', () => {
  const api = read('src/api/product.ts')
  const page = read('src/views/products/edit.vue')
  const listPage = read('src/views/products/index.vue')
  const types = read('src/types/index.ts')

  assert.match(api, /getAdminProductDetail/)
  assert.match(api, /\/admin\/products\/\$\{id\}/)
  assert.match(api, /patch\(`/, '商品上下架应使用后端 PATCH 状态接口')
  assert.match(types, /ProductType = 'daily_camping' \| 'event_camping' \| 'rental'/)
  assert.match(types, /ProductStatus = 'draft' \| 'on_sale' \| 'off_sale'/)
  assert.match(types, /interface ProductImage/)
  assert.match(types, /ext_camping\?:\s*CampingExt/)
  assert.match(types, /free_child_age\?:\s*number \| null/, 'Admin 商品类型应声明儿童免费年龄')
  assert.match(types, /ext_activity\?:\s*ActivityExt/)
  assert.match(types, /ext_rental\?:\s*RentalExt/)
  assert.match(types, /ext_shop\?:\s*ShopExt/)
  assert.match(types, /interface ProductSkuUpsert/)

  assert.match(page, /<el-tabs[\s\S]*基础信息[\s\S]*详情内容[\s\S]*类型属性[\s\S]*SKU/)
  assert.match(page, /v-model="form\.type"/)
  assert.match(page, /daily_camping/)
  assert.match(page, /event_camping/)
  assert.match(page, /rental/)
  assert.match(page, /daily_activity/)
  assert.match(page, /special_activity/)
  assert.match(page, /shop/)
  assert.match(page, /merchandise/)
  assert.match(page, /safeDescriptionPreview/)
  assert.match(page, /sanitizeRichText/)
  assert.doesNotMatch(page, /DOMPurify\.sanitize/)
  assert.match(page, /v-html="safeDescriptionPreview"/)
  assert.doesNotMatch(page, /v-html="form\.description"/)
  assert.match(page, /description:\s*sanitizeRichText\(form\.description/, '商品描述提交前必须净化')
  assert.match(page, /syncDescriptionFromEditor[\s\S]*sanitizeRichText/, '富文本编辑输入必须净化后再写入表单')
  assert.match(page, /form\.images/)
  assert.match(page, /addImage/)
  assert.match(page, /removeImage/)
  assert.match(page, /uploadCmsAsset/, '商品图片应支持直接上传到 CMS 素材接口')
  assert.match(page, /beforeProductImageUpload/, '商品图片上传前应校验图片类型和大小')
  assert.match(page, /handleProductImageUpload/, '商品图片上传成功后应回填图片 URL')
  assert.match(page, /form\.images\.push\(\{ url: asset\.file_url/, '商品图片上传后应写入商品图片列表')
  assert.match(page, /ext_camping\.area/)
  assert.match(page, /campingAreaOptions/, '营位区域应以列表方式维护')
  assert.match(page, /allow-create/, '营位区域应支持新增区域')
  assert.match(page, /filterable/, '营位区域应支持筛选选择')
  assert.match(page, /removeCampingArea/, '营位区域应支持删除')
  assert.match(page, /ext_camping\.position_name/)
  assert.match(page, /ext_camping\.event_start_date/)
  assert.match(page, /ext_activity\.time_slots/)
  assert.match(page, /addTimeSlot/)
  assert.match(page, /ext_rental\.deposit_amount/)
  assert.match(page, /ext_shop\.spec_definitions/)
  assert.match(page, /form\.skus/)
  assert.match(page, /addSku/)
  assert.match(page, /removeSku/)
  assert.match(page, /buildProductPayload/)
  assert.match(page, /on_sale/)
  assert.match(page, /off_sale/)

  assert.match(listPage, /getProductCover/)
  assert.match(listPage, /row\.status === 'on_sale'/)
  assert.doesNotMatch(listPage, /row\.status === 'active'/)
  assert.match(listPage, /formatYuanAmount\(row\.base_price\)/, '商品列表应按后端 Decimal 元金额展示')
  assert.doesNotMatch(listPage, /formatPrice\(row\.base_price\)/, '商品列表不应把后端元金额按分除以 100')
  assert.match(listPage, /\.search-bar[\s\S]*flex-wrap:\s*wrap/, '商品列表筛选栏窄屏应换行')

  assert.match(page, /ensureSkuCode/, 'SKU 编码为空时应在前端生成或阻止提交')
  assert.match(page, /if \(!skuCode\)/, 'SKU 编码生成失败不应提交空编码')
  assert.match(page, /const created = await createProduct/, '新增商品应拿到创建后的商品 ID')
  assert.match(page, /if \(payload\.status && payload\.status !== 'draft'\)[\s\S]*await updateProductStatus/, '新增商品选择上架/下架时应创建后补 PATCH 状态')
  assert.match(page, /throw new Error\('规格定义 JSON 格式错误'\)/, '规格定义 JSON 错误应阻止提交')
  assert.match(page, /function formatSkuSpecText/, 'SKU 规格回填应优先展示运营可读文本')
  assert.match(page, /return \{ '规格': raw \}/, 'SKU 规格应允许直接输入普通文本并转换为规格对象')
  assert.doesNotMatch(page, /SKU \$\{row\.sku_code \|\| '未命名'\} 规格 JSON 格式错误/, 'SKU 规格不应再要求运营手填 JSON')
  assert.match(page, /v-model="row\.image_url"/, '统一商品编辑器应维护 SKU 图片字段')
  assert.match(page, /label="包含人数"/, '营位最大人数字段前台文案应改为包含人数')
  assert.doesNotMatch(page, /label="最大人数"/, '营位属性不应继续展示最大人数旧文案')
  assert.match(page, /campingFreeChildEnabled/, '儿童免费应有显式勾选开关，便于运营开启/关闭')
  assert.match(page, /v-model="campingFreeChildEnabled"/, '儿童免费勾选状态应绑定到表单状态')
  assert.match(page, /const extCampingPayload = \{[\s\S]*\.\.\.form\.ext_camping[\s\S]*free_child_age: campingFreeChildEnabled\.value \? form\.ext_camping\.free_child_age : null/, '关闭儿童免费开关时应在 payload 提交 null，不展示旧年龄')
  assert.doesNotMatch(page, /form\.ext_camping\.free_child_age = campingFreeChildEnabled\.value/, '构造 payload 不应直接修改表单里的儿童免费年龄，避免保存失败丢失输入')
  assert.match(page, /payload\.ext_camping = extCampingPayload/, '营位扩展应提交安全副本')
  assert.match(page, /@media \(max-width: 720px\)/, '编辑器固定列布局应提供窄屏兜底')
})

test('v1.8 admin rich text editors sanitize edit, preview, and emitted html', () => {
  const productEditor = read('src/views/products/edit.vue')
  const cmsRichTextProps = read('src/components/cms/props/RichTextProps.vue')
  const landingRichText = read('src/components/landing/LandingRichText.vue')
  const cmsTypes = read('src/types/cms.ts')
  const richTextUtil = read('src/utils/rich-text.ts')

  assert.match(richTextUtil, /function sanitizeRichText/)
  assert.match(richTextUtil, /FORBID_TAGS:\s*\['script',\s*'style'\]/)

  assert.match(productEditor, /import \{ applyRichTextCommand,\s*sanitizeRichText/)
  assert.match(productEditor, /safeDescriptionPreview = computed\(\(\) => sanitizeRichText\(form\.description/)
  assert.match(productEditor, /description:\s*sanitizeRichText\(form\.description/)
  assert.match(productEditor, /descriptionEditorRef\.value\.innerHTML = sanitized/)
  assert.doesNotMatch(productEditor, /import DOMPurify/)
  assert.doesNotMatch(productEditor, /v-html="form\.description"/)

  assert.match(cmsRichTextProps, /import \{ applyRichTextCommand,\s*sanitizeRichText/)
  assert.match(cmsRichTextProps, /v-html="safeHtml"/)
  assert.match(cmsRichTextProps, /emit\('update:modelValue', \{ content: sanitizedContent \}\)/)
  assert.match(cmsRichTextProps, /editorRef\.value\.innerHTML = sanitizedContent/)
  assert.doesNotMatch(cmsRichTextProps, /import DOMPurify/)
  assert.doesNotMatch(cmsRichTextProps, /v-html="localContent"/)

  assert.match(landingRichText, /import \{ sanitizeRichText \}/)
  assert.match(landingRichText, /safeHtml = computed\(\(\) => sanitizeRichText\(props\.content/)
  assert.doesNotMatch(landingRichText, /import DOMPurify/)
  assert.doesNotMatch(landingRichText, /DOMPurify\.sanitize/)
  assert.match(cmsTypes, /sanitizeRichText/)
  assert.doesNotMatch(cmsTypes, /DOMPurify/)
})

test('v1.8 admin order list maps backend order response and yuan amounts', () => {
  const page = read('src/views/orders/index.vue')
  const types = read('src/types/index.ts')

  assert.match(page, /formatYuanAmount\(row\.total_amount\)/, '订单列表总金额应按后端 Decimal 元展示')
  assert.doesNotMatch(page, /formatPrice\(row\.total_amount\)/, '订单列表不应把后端元金额按分除以 100')
  assert.match(page, /getOrderUserDisplay\(row\)/, '订单列表应兼容后端用户展示字段')
  assert.match(page, /getOrderPhoneDisplay\(row\)/, '订单列表应兼容后端手机号脱敏字段')
  assert.match(page, /getOrderItemCount\(row\)/, '订单列表商品数应由 items 兜底计算')
  assert.match(page, /formatYuanAmount\(row\.refund_amount\)/, '退款队列确认金额应使用 RefundRecord 的退款金额')
  assert.match(types, /actual_amount:\s*number/)
  assert.match(types, /payment_time:\s*string \| null/)
  assert.match(types, /user_phone_masked\?:\s*string \| null/)
})

test('v1.8 admin high-risk modules use super admin only and backend log redaction exists', () => {
  const router = read('src/router/index.ts')
  const layout = read('src/layout/index.vue')
  const settingsPage = read('src/views/system/settings.vue')
  const systemApi = read('src/api/system.ts')
  const highRiskConfirm = read('src/utils/high-risk-confirm.ts')
  const inventoryPage = read('src/views/inventory-pools/index.vue')
  const enterpriseWechatPage = read('src/views/enterprise-wechat/index.vue')
  assert.match(router, /calendar[\s\S]*roles:\s*\['super_admin'\]/, '商品日历路由应与后端库存接口权限保持一致')
  assert.match(layout, /\/calendar', title: '商品日历'[\s\S]*roles: \['super_admin'\]/, '商品日历菜单应只对超管展示')
  assert.match(router, /inventory-pools[\s\S]*roles:\s*\['super_admin'\]/)
  assert.match(router, /enterprise-wechat[\s\S]*roles:\s*\['super_admin'\]/)
  assert.match(settingsPage, /v-if="userStore\.isSuperAdmin"[\s\S]*label="操作密码"/, '操作密码设置入口只应对超管展示')
  assert.match(settingsPage, /操作密码当前用于财务出账、含敏感客户信息的订单导出/, '操作密码说明应与当前已接入高风险操作一致')
  assert.doesNotMatch(settingsPage, /批量删除商品或订单等高风险操作/, '未接入二次确认的批量删除不应被描述为当前已启用范围')
  assert.match(settingsPage, /operationPasswordForm\.oldPassword/, '修改操作密码应支持提交旧操作密码')
  assert.match(settingsPage, /old_password:\s*operationPasswordForm\.oldPassword/, '操作密码 API payload 应包含旧密码字段')
  assert.match(settingsPage, /\^\\d\{6\}\$[\s\S]*operationPasswordForm\.password/, '操作密码应校验 6 位数字')
  assert.match(systemApi, /updateOperationPassword\(data: \{ password: string; old_password\?: string \}\)/, '系统设置 API 应声明旧密码字段')

  const adminRouter = read('../server/routers/admin.py')
  assert.match(adminRouter, /def _redact_enterprise_wechat_log_value/)
  assert.match(adminRouter, /mentioned_mobile_list/)
  assert.match(adminRouter, /def _require_high_risk_confirm/)
  assert.match(adminRouter, /X-Confirm-Token/)
  assert.match(adminRouter, /sku_product_ids/)
  assert.match(adminRouter, /binding_product_id = sku_product_ids\.get\(binding\.sku_id\)/)
  assert.match(adminRouter, /"product_id": binding_product_id/)
  assert.doesNotMatch(adminRouter, /async def create_inventory_pool[\s\S]*_require_high_risk_confirm/)
  assert.doesNotMatch(adminRouter, /async def create_inventory_pool_binding[\s\S]*_require_high_risk_confirm/)
  assert.match(adminRouter, /def _hash_high_risk_body/)
  assert.match(adminRouter, /json\.dumps\([\s\S]*sort_keys=True[\s\S]*separators=\(",",\s*":"\)/)
  assert.match(adminRouter, /hashlib\.sha256/)
  assert.match(adminRouter, /def _get_required_confirm_site_id\(request: Request\) -> int:/, '高风险确认应使用显式站点头解析')
  assert.match(adminRouter, /target_site_id = _get_required_confirm_site_id\(request\)[\s\S]*int\(payload\.get\("site_id"\) or 0\) != target_site_id/, '高风险确认 token 应绑定当前 X-Site-Id 目标站点')
  assert.match(adminRouter, /if not request_hash:/, '高风险写操作必须要求请求内容摘要')

  assert.match(highRiskConfirm, /stableStringify/)
  assert.match(highRiskConfirm, /normalizeJsonPayload/)
  assert.match(highRiskConfirm, /JSON\.parse\(JSON\.stringify\(value \?\? \{\}\)/, '确认 hash 应先按实际 JSON 请求体丢弃 undefined')
  assert.match(highRiskConfirm, /crypto\.subtle\.digest\('SHA-256'/)
  assert.match(highRiskConfirm, /request_hash/)
  assert.match(highRiskConfirm, /payload\?:\s*unknown/)

  const ordersPage = read('src/views/orders/index.vue')
  const ordersApi = read('src/api/order.ts')
  const expensesPage = read('src/views/expense/index.vue')
  const expensesApi = read('src/api/expense.ts')
  const ordersRouter = read('../server/routers/orders.py')
  const expensesRouter = read('../server/routers/expenses.py')
  assert.match(ordersPage, /requestHighRiskConfirm\('orders:export_sensitive'[\s\S]*payload/, '包含敏感字段的订单导出应走高风险确认')
  assert.match(ordersApi, /X-Confirm-Token/, '订单导出 API 应支持确认 token 请求头')
  assert.match(ordersRouter, /orders:export_sensitive/, '后端订单敏感导出应校验确认 action')
  assert.match(expensesPage, /requestHighRiskConfirm\([\s\S]*finance:expense:mark_paid:/, '财务打款标记应走高风险确认')
  assert.match(expensesApi, /X-Confirm-Token/, '财务打款 API 应支持确认 token 请求头')
  assert.match(expensesRouter, /finance:expense:mark_paid:/, '后端财务打款应校验确认 action')

  assert.match(inventoryPage, /ElMessageBox\.confirm\(quantityChange,\s*'共享库存保存确认'/, '库存池保存应使用普通确认')
  assert.match(inventoryPage, /ElMessageBox\.confirm[\s\S]*确认.*共享库存池/, '库存池启停应使用普通确认')
  assert.match(inventoryPage, /ElMessageBox\.confirm[\s\S]*绑定/, '库存池绑定应使用普通确认')
  assert.match(inventoryPage, /deriveBindingProductId/, '编辑 SKU 绑定时应能恢复所属商品上下文')
  assert.match(enterpriseWechatPage, /const payload = buildRobotPayload\(\)[\s\S]*(updateEnterpriseWechatRobot|createEnterpriseWechatRobot)/, '企业微信机器人保存应直接提交 payload')
  assert.match(enterpriseWechatPage, /ElMessageBox\.confirm[\s\S]*updateEnterpriseWechatRobot\(row\.id, \{ status \}/, '企业微信机器人启停应使用普通确认并提交状态 payload')
  assert.match(enterpriseWechatPage, /const payload = \{[\s\S]*mentioned_mobile_list[\s\S]*testSendEnterpriseWechatRobot/, '企业微信测试发送应提交消息 payload')
	assert.match(enterpriseWechatPage, /async function toggleRobotStatus[\s\S]*try \{[\s\S]*ElMessageBox\.confirm[\s\S]*\} catch \{[\s\S]*return[\s\S]*\}/, '企业微信机器人启停取消时不应产生未处理 Promise rejection')
})

test('v1.8 admin membership card module has unified entry, aggregated types, and legacy compat routes', () => {
  const api = read('src/api/member.ts')
  const types = read('src/types/index.ts')
  const router = read('src/router/index.ts')
  const layout = read('src/layout/index.vue')
  const listPage = read('src/views/members/index.vue')
  const detailPage = read('src/views/members/detail.vue')
  const unifiedPage = read('src/views/members/membership-cards.vue')
  const annualPage = read('src/views/members/annual-cards.vue')
  const timesPage = read('src/views/members/times-cards.vue')

  assert.match(api, /getMembershipCards|membership_cards/)
  assert.match(api, /getMembers/)
  assert.match(api, /getMemberDetail/)
  assert.match(types, /membership_cards:\s*MembershipCardInfo\[]/)
  assert.match(types, /membership_card_count:\s*number/)
  assert.match(types, /has_membership_card:\s*boolean/)
  assert.match(types, /interface MembershipCardInfo[\s\S]*card_type:\s*'annual' \| 'times'/)
  assert.match(types, /use_mode:\s*string/)
  assert.match(types, /valid_until:\s*string \| null/)
  assert.match(types, /remaining_days:\s*number \| null/)
  assert.match(types, /remaining_times:\s*number \| null/)
  assert.match(types, /applicable_products:\s*string\[]/)
  assert.match(router, /title:\s*'会员卡'/)
  assert.match(router, /title:\s*'会员卡详情'/)
  assert.match(router, /title:\s*'会员卡配置'/)
  assert.match(router, /path:\s*'members'/)
  assert.match(router, /path:\s*'members\/:id'/)
  assert.match(router, /path:\s*'annual-cards'/)
  assert.match(router, /path:\s*'times-cards'/)
  assert.match(layout, /title:\s*'会员卡'/)
  assert.match(layout, /会员卡总览/)
  assert.match(layout, /年卡配置/)
  assert.match(layout, /次数卡配置/)
  assert.match(listPage, /会员卡/)
  assert.match(listPage, /membership_cards/)
  assert.match(listPage, /membership_card_count/)
  assert.match(listPage, /has_membership_card/)
  assert.match(listPage, /<el-tabs/)
  assert.match(listPage, /年卡/)
  assert.match(listPage, /次数卡/)
  assert.match(detailPage, /会员卡详情/)
  assert.match(detailPage, /membership_cards/)
  assert.match(detailPage, /剩余天数/)
  assert.match(detailPage, /剩余次数/)
  assert.match(detailPage, /适用商品/)
  assert.match(detailPage, /使用模式/)
  assert.match(unifiedPage, /会员卡/)
  assert.match(unifiedPage, /会员卡总览/)
  assert.match(unifiedPage, /年卡配置/)
  assert.match(unifiedPage, /次数卡配置/)
  assert.match(unifiedPage, /membership_cards/)
  assert.match(unifiedPage, /annual/)
  assert.match(unifiedPage, /times/)
  assert.match(unifiedPage, /卡种/)
  assert.match(unifiedPage, /使用模式/)
  assert.match(unifiedPage, /有效期/)
  assert.match(unifiedPage, /剩余天数|剩余次数/)
  assert.match(unifiedPage, /适用商品/)
  assert.match(unifiedPage, /状态/)
  assert.match(annualPage, /兼容入口|会员卡/)
  assert.match(timesPage, /兼容入口|会员卡/)
  assert.match(annualPage, /membership-cards|会员卡/)
  assert.match(timesPage, /membership-cards|会员卡/)
  assert.doesNotMatch(listPage, /年卡管理|次数卡管理/)
  assert.doesNotMatch(detailPage, /年卡信息|次数卡信息/)
})

test('admin requests carry site isolation header for v1.8 multi-campsite APIs', () => {
  const request = read('src/utils/request.ts')

  assert.match(request, /X-Site-Id/)
  assert.match(request, /admin_site_id/)
  assert.match(request, /VITE_SITE_ID/)
  assert.match(request, /auth\/refresh[\s\S]*headers:\s*\{\s*'X-Site-Id':\s*getCurrentSiteId\(\)\s*\}/)
})

test('camp map admin supports hotspot links and click metrics', () => {
  const page = read('src/views/camp-map/index.vue')
  const types = read('src/types/index.ts')

  assert.match(types, /link_type/, '地图区域类型应声明链接类型')
  assert.match(types, /link_target/, '地图区域类型应声明链接目标')
  assert.match(types, /click_count/, '地图区域类型应声明点击次数')
  assert.match(page, /linkTypeOptions/, '地图区域表单应提供链接类型选项')
  assert.match(page, /zoneForm\.link_target/, '地图区域表单应配置链接目标')
  assert.match(page, /prop="click_count"/, '地图区域列表应展示点击次数')
  assert.match(page, /value="image"/, '地图类型应使用后端支持的 image')
  assert.match(page, /value="svg"/, '地图类型应使用后端支持的 svg')
  assert.doesNotMatch(page, /value="plan"|value="satellite"|value="illustration"/, '地图类型不应提交后端不支持的枚举')
  assert.match(page, /uploadCmsAsset/, '地图图片上传应复用统一 CMS 素材上传 API')
  assert.match(page, /:http-request="handleMapImageUpload"/, '地图图片上传不应绕过统一 request 封装')
  assert.doesNotMatch(page, /action="\/api\/v1\/admin\/cms\/assets\/upload"/, '地图图片上传不应写死相对 action')
  assert.match(page, /validateZoneLink/, '地图热区链接应有基础格式校验')
  assert.match(page, /zoneForm\.link_type === 'product'[\s\S]*<el-select[\s\S]*v-model="zoneForm\.link_target"/, '商品热区链接目标应使用商品下拉选择器')
  assert.match(page, /selectedProductIds\.has\(target\)/, '商品热区链接目标应校验来自商品列表')
  assert.doesNotMatch(page, /商品链接目标必须填写商品ID/, '商品热区链接不应要求运营手填商品ID')
  assert.match(page, /map-zone-overlay/, '后台地图预览应叠加展示热区框，便于运营校准坐标')
  assert.match(page, /圈选区域/, '地图应支持运营在图片上圈选区域')
  assert.match(page, /handleMapMouseDown/, '地图圈选应监听拖拽开始')
  assert.match(page, /handleMapMouseMove/, '地图圈选应监听拖拽过程')
  assert.match(page, /handleMapMouseUp/, '地图圈选应把拖拽框转成百分比坐标')
  assert.match(page, /zoneForm\.zone_code = generateZoneCode\(\)/, '区域编码应自动生成，避免运营手填')
  assert.match(page, /placeholder="保存时自动生成" disabled/, '区域编码输入应禁用手填')
  assert.match(page, /class="map-preview-canvas"[\s\S]*<img[\s\S]*class="map-image"/, '热区预览应锚定真实图片元素，而不是 el-image contain 留白容器')
  assert.match(page, /\.map-preview-canvas[\s\S]*display:\s*inline-block/, '热区预览容器应由图片实际尺寸撑开')
  assert.match(page, /validateZoneCoordinates/, '地图热区坐标应有越界校验')
  assert.match(page, /x \+ width/, '坐标校验应限制热区宽度不能超出底图')
  assert.match(page, /y \+ height/, '坐标校验应限制热区高度不能超出底图')
  assert.match(types, /CampMapType = 'image' \| 'svg'/, '地图类型应在 TS 层收窄为后端枚举')
  assert.equal(page.includes("!/^https:\\/\\//.test(target)"), true, 'H5 热区链接应限制 HTTPS')
  assert.match(page, /H5 链接必须以 https:\/\/ 开头/, 'H5 热区链接应给出 HTTPS 提示')
  assert.match(page, /\.coordinates-row[\s\S]*flex-wrap:\s*wrap/, '坐标输入在窄屏弹窗内应允许换行')
  assert.match(page, /flex:\s*1 1 110px/, '坐标输入宽度应响应式伸缩')
  assert.match(page, /商品列表加载失败/, '商品链接下拉加载失败时应提示运营')
})

test('new miniapp demand admin UX covers cloud files qrcode picker and product editor fixes', () => {
  const router = read('src/router/index.ts')
  const layout = read('src/layout/index.vue')
  const cmsApi = read('src/api/cms.ts')
  const cloudFiles = read('src/views/cloud-files/index.vue')
  const productEditor = read('src/views/products/edit.vue')
  const productList = read('src/views/products/index.vue')
  const qrcodePage = read('src/views/qrcodes/index.vue')
  const cmsPage = read('src/views/cms/index.vue')
  const linkPicker = read('src/components/cms/LinkPicker.vue')
  const productListProps = read('src/components/cms/props/ProductListProps.vue')
  const imageProps = read('src/components/cms/props/ImageProps.vue')
  const imageTextProps = read('src/components/cms/props/ImageTextProps.vue')
  const componentPanel = read('src/components/cms/ComponentPanel.vue')
  const cmsEditor = read('src/views/cms/editor.vue')
  const adminCmsTypes = read('src/types/cms.ts')
  const landingImageText = read('src/components/landing/LandingImageText.vue')

  assert.match(router, /path: 'cloud-files'/, '内容管理应新增云文件路由')
  assert.match(layout, /\/cloud-files', title: '云文件'/, '内容管理菜单应展示云文件')
  assert.match(layout, /\/qrcodes', title: '二维码管理'/, '内容管理菜单应能找到二维码管理')
  assert.doesNotMatch(layout, /\/inventory-pools', title: '共享库存'/, '运营菜单不应继续展示独立共享库存入口')
  assert.doesNotMatch(layout, /\/campsites', title: '营位管理'/, '运营菜单不应继续展示重复营位管理入口')
  assert.match(cloudFiles, /上传图片/, '云文件应包含图库上传')
  assert.match(cloudFiles, /复制 URL/, '云文件应支持复制外链 URL')
  assert.match(cloudFiles, /二维码源文件/, '云文件应集中展示二维码源文件')
  assert.match(cloudFiles, /导出营位信息/, '云文件应提供导出数据入口')
  assert.match(cloudFiles, /file_type: 'qrcode'/, '二维码源文件应从云文件资产归档读取')
  assert.match(cloudFiles, /file_type: 'export'/, '导出数据应从云文件资产归档读取')
  assert.match(cloudFiles, /exportCampsiteInfoAsset/, '导出营位信息应调用后端生成并归档云文件')
  assert.match(cloudFiles, /handleDeleteAsset\(row\.id,\s*'qrcode'\)/, '二维码源文件也应能从云文件中删除并刷新列表')
  assert.match(cloudFiles, /handleDeleteAsset\(row\.id,\s*'export'\)/, '导出数据也应能从云文件中删除并刷新列表')
  assert.match(cloudFiles, /await fetchQrcodes\(\)/, '删除二维码源文件后应刷新二维码文件列表')
  assert.match(cloudFiles, /await fetchExports\(\)/, '删除导出文件后应刷新导出文件列表')
  assert.match(cmsApi, /uploadCmsAsset[\s\S]*headers:\s*\{[\s\S]*'Content-Type':\s*'multipart\/form-data'/, '素材上传必须覆盖默认 JSON Content-Type，避免 FormData 被 Axios 转成 JSON')
  assert.match(cmsApi, /\/admin\/cms\/assets\/export\/campsites/, '云文件 API 应提供后端营位信息导出归档接口')

  assert.match(productEditor, /业务分类用于前台筛选、装修组件和运营统计/, '业务分类应有含义说明')
  assert.match(productEditor, /日常活动通过“场次”设置每天可预约时间/, '活动时间设置应有说明')
  assert.match(productEditor, /slot-capacity-field[\s\S]*库存/, '活动场次容量数字前应标库存')
  assert.match(productEditor, /<el-table-column label="规格"/, 'SKU 表格应使用普通规格文案，不应引导运营填写 JSON')
  assert.doesNotMatch(productEditor, /<el-table-column label="规格 JSON"/, 'SKU 表格不应继续展示规格 JSON 列名')
  assert.match(productEditor, /handleDescriptionImageUpload/, '商品富文本应支持上传图片插入')
  assert.match(productEditor, /商品新建时先选择库存类型/, '商品新建时应能选择库存类型')
  assert.match(productEditor, /v-model="form\.sku_inventory_mode"/, '商品编辑器应提供默认 SKU 库存模式')
  assert.match(productEditor, /v-model="row\.inventory_mode"/, '同一商品不同 SKU 应可单独选择是否共享库存')
  assert.match(productEditor, /inventory_mode:\s*row\.inventory_mode \|\| 'independent'/, '保存 SKU 时应提交库存模式')
  assert.match(productEditor, /本商品共享库存/, '共享库存文案应限定为本商品内共享')
  assert.doesNotMatch(productEditor, /v-html="safeDescriptionPreview"[\s\S]*contenteditable/, '富文本编辑区不应通过 v-html 每次输入重渲染导致光标跳动')

  assert.match(productList, /openQrcodePreview/, '商品二维码生成后应直接打开预览')
  assert.match(productList, /下载透明底 PNG/, '商品二维码预览应提供透明底 PNG 下载')
  assert.doesNotMatch(productList, /可在二维码管理中查看/, '商品二维码生成后不应只提示去二维码管理')
  assert.match(qrcodePage, /previewVisible/, '二维码管理页应真实预览二维码图片')
  assert.match(qrcodePage, /下载透明底 PNG/, '二维码管理页应支持透明底 PNG 下载')
  assert.match(cmsPage, /openQrcodeDialog/, 'CMS 页面二维码生成后应直接弹出预览')

  assert.match(linkPicker, /remote-method="searchProducts"/, '链接选择器商品目标应搜索选择')
  assert.match(linkPicker, /categoryOptions/, '链接选择器分类目标应下拉选择')
  assert.match(linkPicker, /getCmsPages/, '链接选择器活动页目标应从 CMS 页面选择')
  assert.match(linkPicker, /pageOptions/, '链接选择器活动页应维护可选 CMS 页面列表')
  assert.match(linkPicker, /v-model="localLink\.target"[\s\S]*pageOptions/, 'CMS 活动页不应继续手填页面 ID')
  assert.match(linkPicker, /watch\(\s*\(\) => props\.visible[\s\S]*syncLocalLink/, '链接选择器每次打开都应从 modelValue 回滚本地状态')
  assert.doesNotMatch(linkPicker, /placeholder="输入商品ID"/, '链接选择器不应要求手填商品 ID')
  assert.doesNotMatch(linkPicker, /placeholder="输入分类ID"/, '链接选择器不应要求手填分类 ID')
  assert.doesNotMatch(linkPicker, /placeholder="CMS页面ID"/, '活动页链接不应要求手填 CMS 页面 ID')
  assert.match(productListProps, /multiple[\s\S]*remote-method="searchProducts"/, '商品列表组件手动商品应多选')
  assert.match(productListProps, /v-model="localProps\.category_key"/, '商品列表组件分类应选择 category_key')
  assert.match(productListProps, /legacyCategoryIdMap/, '商品列表组件应兼容旧 category_id 配置')
  assert.doesNotMatch(linkPicker, /value: 'campsite'|value: 'activity'|value: 'rental'|value: 'shop'/, '链接分类选择器不应暴露不可消费的聚合分类值')
  assert.doesNotMatch(productListProps, /value: 'campsite'|value: 'activity'|value: 'rental'|value: 'shop'/, '商品列表分类选择器不应暴露不可消费的聚合分类值')
  assert.match(linkPicker, /value: 'equipment_rental'/, '链接分类选择器应使用小程序可消费的装备租赁 tab key')
  assert.match(linkPicker, /value: 'camp_shop'/, '链接分类选择器应使用小程序可消费的小商店 tab key')
  assert.match(productListProps, /value: 'equipment_rental'/, '商品列表分类选择器应使用小程序可消费的装备租赁 tab key')
  assert.match(productListProps, /value: 'camp_shop'/, '商品列表分类选择器应使用小程序可消费的小商店 tab key')
  assert.match(imageTextProps, /v-model="localProps\.title_font_size"/, '图文卡片标题字号应可配置')
  assert.match(imageTextProps, /v-model="localProps\.desc_font_size"/, '图文卡片描述字号应可配置')
  assert.match(imageTextProps, /v-model="localProps\.title_font_family"/, '图文卡片标题字体应可配置')
  assert.match(imageTextProps, /v-model="localProps\.desc_font_family"/, '图文卡片描述字体应可配置')
  assert.match(imageTextProps, /v-model="localProps\.title_font_weight"/, '图文卡片标题字重应可配置')
  assert.match(imageTextProps, /v-model="localProps\.desc_font_weight"/, '图文卡片描述字重应可配置')
  assert.match(componentPanel, /title_font_size:\s*32/, '图文卡片默认配置应包含标题字号')
  assert.match(componentPanel, /desc_font_size:\s*26/, '图文卡片默认配置应包含描述字号')
  assert.match(componentPanel, /title_font_family:\s*'system'/, '图文卡片默认配置应包含标题字体')
  assert.match(cmsEditor, /title_font_family:\s*'system'/, 'CMS 编辑器默认图文卡片应包含字体配置')
  assert.match(adminCmsTypes, /title_font_family:\s*string/, 'Admin CMS 图文卡片类型应声明标题字体')
  assert.match(adminCmsTypes, /desc_font_weight:\s*string/, 'Admin CMS 图文卡片类型应声明描述字重')
  assert.match(landingImageText, /fontFamily:\s*previewFontFamily\(title_font_family\)/, 'Admin 预览应消费标题字体')

  assert.match(imageProps, /hotspots:\s*\[\]/, '图片组件应初始化热区配置')
  assert.match(imageProps, /hotspot-canvas/, '图片组件应提供热区圈选画布')
  assert.match(imageProps, /handleHotspotMouseDown/, '图片组件热区应支持拖拽开始')
  assert.match(imageProps, /handleHotspotMouseMove/, '图片组件热区应支持拖拽过程')
  assert.match(imageProps, /handleHotspotMouseUp/, '图片组件热区应把拖拽框保存为百分比坐标')
  assert.match(imageProps, /LinkPicker[\s\S]*v-model="activeHotspot\.link"/, '图片热区应使用链接选择器设置目标')
  assert.match(adminCmsTypes, /hotspots:\s*ImageHotspotConfig\[\]/, '图片组件类型应声明热区列表')
})

test('reports page exposes page view analytics', () => {
  const reportsPage = read('src/views/reports/index.vue')
  const systemApi = read('src/api/system.ts')

  assert.match(systemApi, /getPageViewStats/, '后台应封装页面浏览统计 API')
  assert.match(systemApi, /\/admin\/analytics\/page-views/, '页面浏览统计 API 路径应正确')
  assert.match(systemApi, /summary:\s*PageViewSummary/, '页面浏览统计响应应包含后端全量聚合摘要')
  assert.match(reportsPage, /value="page_views"/, '报表页应有页面浏览类型入口')
  assert.match(reportsPage, /getPageViewStats/, '报表页应拉取页面浏览统计')
  assert.match(reportsPage, /pageViewSummary/, '报表页应展示页面浏览摘要')
  assert.doesNotMatch(reportsPage, /reduce\(\(sum,\s*item\)\s*=>\s*sum \+ item\.view_count/, '页面浏览摘要不应从第一页列表汇总')
})
